/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:59532778-d9d9-4b33-8a73-3dfaf60adf65",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_NyKbA8bp1",
    "aws_user_pools_web_client_id": "4m6gh95rvgt53cvu8socjj7n9r",
    "oauth": {},
    "aws_user_files_s3_bucket": "aws-news22e8b0b356ca40dabae23f3b3e7ab9f0dev-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://rqodarqrcjg4ncmx75drkebbdy.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_mobile_analytics_app_id": "9dbf835e91034bed9d700adc2a813910",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
